# Find all the available rules by running:
# swiftlint rules

disabled_rules: # rule identifiers to exclude from running
  - type_name
  - trailing_whitespace
  - identifier_name
  - trailing_comma
  - cyclomatic_complexity
  - opening_brace
  #- class_delegate_protocol
  - nesting
  - function_body_length
  - type_body_length
  - function_parameter_count
  - file_length
  - unused_closure_parameter
  - comment_spacing
  - inclusive_language
  
opt_in_rules: # some rules are only opt-in
 # - empty_count
 # - missing_docs
 # - cyclomatic_complexity
  - fatal_error_message

excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Carthage
 - Pods
 - DocketCore/Sources/Utilities/Date Utilities
 - DocketCore/Sources/TextEditor
 - .build

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly

# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 550

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle)

